stranger_code = [{'duration': 42,
                  'number': 1,
                  'title': 'Installing the softwares',
                  'viewed': True},
                 {'duration': 51, 'number': 2, 'title': 'It works !', 'viewed': True},
                 {'duration': 47,
                  'number': 3,
                  'title': 'It does not work anymore',
                  'viewed': True},
                 {'duration': 46, 'number': 4, 'title': 'Launching the debug', 'viewed': True},
                 {'duration': 42,
                  'number': 5,
                  'title': 'Did someone read the doc ?',
                  'viewed': False},
                 {'duration': 58,
                  'number': 6,
                  'title': 'Trying that stuff from Stack Overflow…',
                  'viewed': False},
                 {'duration': 51,
                  'number': 7,
                  'title': 'The client wants a demo',
                  'viewed': False},
                 {'duration': 72, 'number': 8, 'title': 'Release Day !', 'viewed': False}]
